---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
    tags:
      - v*
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@29d3bd9b176d306bd566bf65f7ace08860ff5b6c # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
